//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace akhbarna.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    
    public partial class news
    {
        public news()
        {
            this.comments = new HashSet<comment>();
        }

        public int id { get; set; }
        [Required(ErrorMessage = "ÇÏÎá ÚäæÇä ÇáÎÈÑ")]
        [RegularExpression(".{5,80}", ErrorMessage = "ÚäæÇä ÇáÎÈÑ íÌÈ Çä íÍÊæí Úáí ÇáÇŞá 5 ÍÑæİ æ Úáí ÇáÃßËÑ 80 ÍÑİ")]
        [Display(Name = "ÚäæÇä ÇáÎÈÑ")]
        public string title { get; set; }
        [Required(ErrorMessage = "ÇÏÎá ÊÕäíİ ÇáÎÈÑ")]
        [Display(Name = "ÇáİÆÉ")]
        public string category { get; set; }
        [Required(ErrorMessage = "ÇÏÎá ÕæÑÉ ááÎÈÑ")]
        [Display(Name = "ÕæÑÉ ÇáÎÈÑ")]
        [NotMapped]
        public HttpPostedFileBase imagelink { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        [Required(ErrorMessage = "ÇÏÎá ÊİÇÕíá ÇáÎÈÑ")]
        [Display(Name = "ÊİÇÕíá ÇáÎÈÑ")]
        public string details { get; set; }
        public Nullable<int> views { get; set; }
    
        public virtual ICollection<comment> comments { get; set; }
    }
}
